### ISSUE TITLE
For Testing Section: commands not work, from Contributing.md file

### ISSUE THREAD

**Issue by dareerahmadmufti** [supertokens/supertokens-fastapi#10]
I am using windows 10, with VS code as editor and CMD for the command-prompt/terminal.

I am trying to build the project with the given commands [in Contributing.md file], and I think majority of them are not written for windows system. I have converted, find alternative and used all of the commands before the testing section. 
In testing section, the commands isn't working at all.
Have you any windows equivalent or alternative command for this.
./startTestingEnv --wait

Even if you have tell, what this command is doing, I maybe able to find its alternative.

**Comment by rishabhpoddar** [comment]
It will be very difficult for us to port the dev setup to Windows at the moment.

That being said, `./startTestingEnv` is a script located [here](https://github.com/supertokens/supertokens-root/blob/master/startTestingEnv).
