### ISSUE TITLE
Understand FastAPI SDK

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-fastapi#19]

**Comment by vasica38** [comment]
Meanwhile writing unit tests for fast api sdk, I noticed some things which are different from fast api sdk and node sdk. 

For instance, supertokens in the node sdk can be initiated without supertokens connection url and by doing the same on the fast api sdk is trowing an error. I guess both sdks should act in the same way.   
Another example which confused me is the setting of the api keys in the product. In the yaml file of the core there is "api_keys" meanwhile in the sdk it is used 'api_key'. "api_keys" can have multiple values? 
@rishabhpoddar

**Comment by rishabhpoddar** [comment]
@vasica38 , yes, `api_keys` in the core can have multiple values, but only one of them needs to be provided in the SDK. This is confusing.. you are correct. The reason we have multiple api keys in the core is so that one can change the API key gradually.. if we had just one API key, and that would need to be changed, then all the clients using the older one would stop working. 

Any suggestions for how to make all this clear and more intuitive?

**Comment by vasica38** [comment]
@rishabhpoddar  perhaps renaming api_keys to api_key in the core side. In the end,  it is just a suggestion and I don't fully know if a normal user who is implementing any of the sdk will have to "touch" the api_keys from the core. Hope I was clear.

**Comment by rishabhpoddar** [comment]
They will need to "touch" that only if they are self hosting the core.

**Comment by vasica38** [comment]
@rishabhpoddar if you find this an issue which has to be solved, let me know and I will create a ticket. 

what do you think about the first issue from above?

**Comment by rishabhpoddar** [comment]
@vasica38 the connection uri issue seems to be an issue that you can solve in the python SDK. I'm not sure I entirely understand the issue you pointed out though. But it's OK for now.. we can discuss this when you are making the python repo.

**Comment by vasica38** [comment]
![image.png](https://images.zenhubusercontent.com/61079725f31b48700d4d4f62/9052743d-4934-43fc-be7e-4b388ea465e9)
In this example we can notice the connection_url. 

In the node sdk -> you can instantiate the supertokens lib without connection_url
int the python sdk -> you cannot instantiate the supertokens lib without connection_url

Ok. We will come back later

**Comment by rishabhpoddar** [comment]
oh right! understood.. yea this is cause the fastapi SDK is way behind the node SDK and the connection_uri being optional is something that was added later on in the node sdk
