### ISSUE TITLE
Add tests for Auth0 handler

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-fastapi#3]
- General auth0 handler tests
- When the axios call in Auth0 handler returns 403, make sure that the API itself returns 403
- When session has expired and the auth0 handler is being called, make sure it returns the right status code

**Comment by bhumilsarvaiya** [comment]
tests are have been added to this [commit](https://github.com/supertokens/supertokens-fastapi/tree/2100b23c5751a16fa3215fa043dde1f306bd53fd).
